### PR TITLE
SHUT THE FUCK UP

### PR DESCRIPTION
**Pull request by ValkyrieSkies**
NO ONE ASKED YOU ANNOYING MOTHERFUCKER

Deletes some of the stupid annoying responses like "When you code it" and "Based on what?"

### CODE REVIEW

**Comment by Squird5** [comment]
Based on what?

**Comment by Exxion** [comment]
cringe

**Comment by Exxion** [comment]
I didn't even know about half of these
I'm surprised you didn't also remove "Works on my machine"

works on my when

**Comment by ValkyrieSkies** [comment]
> I didn't even know about half of these I'm surprised you didn't also remove "Works on my machine"
> 
> works on my when

That was actually a MoMMI v1 function, it's not on v2.

**Comment by Exxion** [comment]
Huh. Never noticed

**Pull request closed without merging**
